### ISSUE TITLE
feature request: hide title

### ISSUE THREAD

**Issue by PeterMosmans** [attakei/sphinx-revealjs#163]
Hi,

Would it be possible to implement the property `:notitle:` in the `.. revealjs-slide` directive? Currently (as far as I can tell) there is no option to easily hide the *title* from a section.

Thanks for your consideration, great extension 👍

**Comment by attakei** [comment]
Thank you for idea! It would be useful to have it.

I think that it may be possible to implement but less easy than `revealjs-break` directive.

- When `revealjs-break` is found, writer copy previous title if `:notitle: is not set (it is ADDING action)
- But write need remove title from section if `revealjs-slide` directive having `:notitle:` (it is DELETING action)

**Comment by attakei** [comment]
If you want to hide only title text on first section of vertical sections, try approarch using CSS as workaround.

```css
/* Example to hide title of second vertical section */
section:nth-child(2) h2 {
  display: none;
}
```

**Comment by PeterMosmans** [comment]
Thanks for the hints @attakei : For now I solved it with
```rest
.. revealjs-section::
   :data-state: notitle
```

and then in CSS:

```css
.notitle h2 {
  opacity: 0;
}
```

It's sub-optimal, as the title is briefly shown when the next slide appears, but for now definitely workable.

If you don't mind I'd like to keep this issue open for potential consideration.
